channel1:
  auto_water: false
  dry_point: 26
  enabled: true
  pump_speed: 1
  pump_time: 2
  warn_level: 0.2
  watering_delay: 60
  wet_point: 0.5
channel2:
  auto_water: true
  dry_point: 27
  enabled: true
  pump_speed: 1
  pump_time: 2
  warn_level: 0.2
  watering_delay: 60
  wet_point: 0.5
channel3:
  auto_water: true
  dry_point: 27
  enabled: true
  pump_speed: 1
  pump_time: 2
  warn_level: 0.2
  watering_delay: 60
  wet_point: 0.5
general:
  alarm_enable: true
  alarm_interval: 2
  light_level_low: 4.0
  black_screen_when_light_low: true
